

import tools

from login import Login
import simplejson as json
from JzwLessonM3u8Downloader import JzwLessonM3u8Downloader 
from JzwCourseM3u8Downloader import JzwCourseM3u8Downloader 

# Java架构师体系课：跟随千万级项目从0到100全过程高效成长
def download1():
    session = Login().login()
    save_path = tools.join_path(tools.main_path(), "下载")
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1222", path=save_path+"\Java架构师体系课",course_name="第1周.万丈高楼，地基首要").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1223", path=save_path+"\Java架构师体系课",course_name="第2周.分类，推荐，搜索，评价，购物车开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1224", path=save_path+"\Java架构师体系课",course_name="第3周.地址，订单，支付，定时任务开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1225", path=save_path+"\Java架构师体系课",course_name="第4周.用户中心 ,订单/评价管理开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1226", path=save_path+"\Java架构师体系课",course_name="第5周.云服务器部署上线").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1227", path=save_path+"\Java架构师体系课",course_name="第6周.LVS+Nginx实现高可用集群").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1228", path=save_path+"\Java架构师体系课",course_name="第7周.主从复制高可用Redis集群").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1229", path=save_path+"\Java架构师体系课",course_name="第8周.Redis缓存雪崩，穿透").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1230", path=save_path+"\Java架构师体系课",course_name="第9周.分布式会话与单点登录SSO").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1231", path=save_path+"\Java架构师体系课",course_name="第10周.分布式搜索引擎-ES").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1232", path=save_path+"\Java架构师体系课",course_name="第11周.分布式文件系统-FastDFS+OSS").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1233", path=save_path+"\Java架构师体系课",course_name="第12周.分布式消息队列-RabbitMQ").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1234", path=save_path+"\Java架构师体系课",course_name="第13周.分布式消息队列-Kafka").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1235", path=save_path+"\Java架构师体系课",course_name="第14周.分布式锁").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1236", path=save_path+"\Java架构师体系课",course_name="第15周.读写分离、分库分表").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1237", path=save_path+"\Java架构师体系课",course_name="第16周.分布式全局ID、分布式事务和数据一致性").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1238", path=save_path+"\Java架构师体系课",course_name="第17周.分布式接口幂等性，分布式限流").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1239", path=save_path+"\Java架构师体系课",course_name="第18周.微服务架构认知、服务治理-Eureka").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1240", path=save_path+"\Java架构师体系课",course_name="第19周.负载均衡、服务通信与调用").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1241", path=save_path+"\Java架构师体系课",course_name="第20周.服务容错-Hystrix").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1242", path=save_path+"\Java架构师体系课",course_name="第21周.分布式配置中心-Config").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1243", path=save_path+"\Java架构师体系课",course_name="第22周.消息总线、服务网关").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1244", path=save_path+"\Java架构师体系课",course_name="第23周.服务调用链追踪、消息驱动").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1245", path=save_path+"\Java架构师体系课",course_name="第24周.微服务下Sentinel流量防控卫兵").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1246", path=save_path+"\Java架构师体系课",course_name="第25周.服务治理的另一条路 - Dubbo").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1247", path=save_path+"\Java架构师体系课",course_name="第26周.服务容器化-Docker").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1248", path=save_path+"\Java架构师体系课",course_name="第27周.容器技术-Cloud Foundry").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1249", path=save_path+"\Java架构师体系课",course_name="第28周.容器编排-Mesos+ Marathon").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1250", path=save_path+"\Java架构师体系课",course_name="第29周.容器编排-K8S").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1251", path=save_path+"\Java架构师体系课",course_name="第30周.容器弹性扩缩容").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1252", path=save_path+"\Java架构师体系课",course_name="第31周.高性能网络通信基石-Netty入门与提高").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1253", path=save_path+"\Java架构师体系课",course_name="第32周.高性能网络通信基石-Netty最佳实战").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1254", path=save_path+"\Java架构师体系课",course_name="第33周.基于Netty打造RPC通信框架-1").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1255", path=save_path+"\Java架构师体系课",course_name="第34周.基于Netty打造RPC通信框架-2").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1256", path=save_path+"\Java架构师体系课",course_name="第35周.应用监控与调优-工具篇").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1257", path=save_path+"\Java架构师体系课",course_name="第36周.应用监控与调优-技巧与实战篇").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1258", path=save_path+"\Java架构师体系课",course_name="第37周.JVM性能调优-理论+工具篇").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1259", path=save_path+"\Java架构师体系课",course_name="第38周.JVM性能调优-实战篇").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1260", path=save_path+"\Java架构师体系课",course_name="第39周.数据库监控与调优").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1261", path=save_path+"\Java架构师体系课",course_name="第40周.Linux调优与架构调优").download_m3u8()
# download1()

# 大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）
def download2():
    session = Login().login()
    save_path = tools.join_path(tools.main_path(), "下载")
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1160", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第1周.认识大前端，开启无限可能").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1163", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第1.5周.前端框架分类及选型").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1159", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第2周.企业标准的开发环境搭建").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1161", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第3周.必会的前端工程化工具").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1167", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第4周.NoSQL数据库的设计与集成").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1168", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第5周.JWT登录鉴权—通用登录模块后端开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1162", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="5.5选修周.深入理解Vue2框架知识（选修）").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1759", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第6周.团队协作-文档管理与缺陷控制").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1164", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第7周.团队协作-版本管理").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1165", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第8周.团队协作-自动化流程").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1169", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第9周.全栈开发—首页模块").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1284", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第10周.全栈开发—用户中心").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1761", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第11周.全栈开发—发贴/回帖模块").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1182", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第12周.消息中间件开发（WebSocket通信）").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1170", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第13周.性能优化--服务端渲染").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1171", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第14周.组件化思想进阶：iview上手文章管理").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1172", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第15周.中后台权限系统：前端权限设计方案").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1173", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第16周.中后台权限系统：基于角色&菜单权限设计").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1174", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第17周.首页可视化图表与日志服务").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1175", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第18周.WebApp页面设计与开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1176", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第19周.WebApp前后端联调").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1177", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第20周.小程序基础与进阶").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1179", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第21周.小程序首页/菜单定制/登录开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1180", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第22周.小程序详情面/个人中心开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1178", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第23周.小程序编辑与发贴开发").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1181", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第24周.项目部署、运维与展望").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1751", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第25周.Vue3带来的新特性").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1752", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第26周.Vue3全家桶+Vite开发工具").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1753", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第27周.PC端项目Vue3首页重构").download_m3u8()
    JzwCourseM3u8Downloader(session,  "https://class.imooc.com/course/1754", path=save_path+"\大前端：前端全栈加强版！前端全栈+全周期+多端（升级Vue3.0）",course_name="第28周.管理后台&WebApp代码重构").download_m3u8()
download2()
